language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mydockerusername/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mydockerusername/docker-react npm run test